export const radomQuestions=// 20230206084000
// https://cdn.simplelocalize.io/57157aec81d54cb6b2a43f8b34a61d47/_production/vi

{
  "PROMPTS.TRUTH_OR_DARE": "nói thật hay thử thách, t sẽ làm thật luôn",
  "FAKE_QUESTIONS.WHOS_YOUR_LAST_SNAP_FROM": "tin snap gần đây nhất của c là từ ai?",
  "REENGAGEMENT.SUBTEXT.MONDAY17": "Nhấp ngay!",
  "REENGAGEMENT.SUBTEXT.MONDAY18": "Nhấp vào đây!",
  "HOME.PLAY_SCREEN.TUTORIAL.STEPS.TWO.TITLE.TWO": "hình dán",
  "FAKE_QUESTIONS.ARE_YOU_GONNA_GET_A_TAT": "cậu có định xăm không",
  "HOME.PLAY_SCREEN.TUTORIAL.STEPS.TWO.TITLE.ONE": "Nhấp vào",
  "REENGAGEMENT.SUBTEXT.SUNDAY18": "Nhấp vào đây!",
  "GENERAL.YES": "Có",
  "HOME.PLAY_SCREEN.STEP_ONE.BUTTON": "sao chép liên kết",
  "FAKE_QUESTIONS.THE_WORST_PICK_UP_LINE_YOUVE_EVER_HEARD": "câu tán nản nhất cậu từng nghe?",
  "REENGAGEMENT.SUBTEXT.SUNDAY17": "Nhấp vào đây!",
  "FAKE_QUESTIONS.WHOS_THE_LAST_PERSON_YOU_TEXTED": "ai là người c nhắn tin gần đây nhất?",
  "SETTINGS.DELETE_MODAL.BUTTON": "Xóa",
  "FAKE_QUESTIONS.HOW_MANY_HOURS_OF_SLEEP_YOU_GET_LAST_NIGHT": "đêm qua cậu ngủ mấy tiếng?",
  "SETTINGS.TITLE": "Cài đặt",
  "FAKE_QUESTIONS.WHERE_ARE_YOUR_PARENTS_FROM": "bố mẹ cậu quê ở đâu?",
  "REENGAGEMENT.SUBTEXT.TUESDAY18": "Nhấp ngay!",
  "GAMES.PROMPTS.CONFESSIONS": "gửi cho mình tin nhắn ẩn danh",
  "FAKE_QUESTIONS.HAVE_ANY_NETLIX_RECOMENDATIONS": "c có đề xuất xem gì trên netflix ko?",
  "FAKE_QUESTIONS.WHATS_UR_FAV_BOOK": "c thích nhất quyển sách nào",
  "FAKE_QUESTIONS.WHAT_TIME_DO_YOU_USUALLY_GO_TO_BED": "thường c đi ngủ lúc mấy giờ?",
  "REENGAGEMENT.TUESDAY18": "Bạn muốn thêm tin nhắn? 💌",
  "HOME.PLAY_SCREEN.NAME": "Chia sẻ",
  "FAKE_QUESTIONS.WHO_WAS_THE_LAST_GIRL_YOU_TEXTED": "mới nhắn với em nào gần đây nhất?",
  "FAKE_QUESTIONS.WHERE_ARE_YOU_FROM": "c quê ở đâu…?",
  "QUESTION.HINTS.LOCATION.DESCRIPTION": "gần",
  "FAKE_QUESTIONS.HOW_MANY_KIDS_DO_YOU_WANT_TO_HAVE": "cậu muốn có mấy đứa con?",
  "QUESTION.PAYWALL.RENEWAL.ONE": "pro được gia hạn cho",
  "FAKE_QUESTIONS.HAVE_YOU_EVER_HAD_ANY_SURGERY": "cậu đã bao giờ phẫu thuật chưa",
  "FAKE_QUESTIONS.THE_WORST_TROUBLE_YOU_GO_INTO_AS_A_KID": "pha gay go nhất cậu từng lâm vào hồi bé?",
  "FAKE_QUESTIONS.TELL_ME_A_RANDOM_FACT": "kể một sự thật ngẫu nhiên đi",
  "GENERAL.CLOSE": "Đóng",
  "FAKE_QUESTIONS.AINT_NO_WAY": "không đời nào",
  "FAKE_QUESTIONS.WOULD_YOU_LEAVE_YOUR_FOR_A_CELEB": "c có bao giờ bỏ ny để đi với người nổi tiếng ko",
  "GENERAL.ARE_YOU_SURE": "Bạn có chắc không?",
  "FAKE_QUESTIONS.WHATS_UR_FAV_MOVIE": "c thích phim nào nhất",
  "HOME.PLAY_SCREEN.TUTORIAL.STEPS.ONE.TITLE.TWO": "nút",
  "QUESTION.HINTS.CARRIER": "nhà mạng/isp",
  "HOME.PLAY_SCREEN.TUTORIAL.TITLE.TWITTER": "Chia sẻ liên kết NGL của bạn lên Twitter",
  "FAKE_QUESTIONS.WHO_WAS_THE_LAST_DUDE_YOU_TEXTED": "mới nhắn với anh nào gần đây nhất?",
  "FAKE_QUESTIONS.DO_YOU_EVEN_LIKE_SCHOOL": "cậu có thích đi học không?",
  "FAKE_QUESTIONS.WHEN_WAS_THE_LAST_TIME_YOU_LIED": "lần cuối c nói dối là khi nào?",
  "FAKE_QUESTIONS.SPILL_THE_TEA_ON_YOUR_FIRST_KISS": "kể về nụ hôn đầu đi",
  "QUESTION.PAYWALL.RENEWAL.TERMS": "Điều khoản",
  "FAKE_QUESTIONS.WHAT_WAS_UR_WORST_DAY_EVER": "ngày tệ nhất của c là gì",
  "FAKE_QUESTIONS.THE_WEIRDEST_THING_YOUVE_EVER_EATEN": "thứ dị nhất mà cậu từng ăn?",
  "ONBOARDING.SECOND_STEP.BUTTON": "Xong!",
  "FAKE_QUESTIONS.DO_YOU_MEDITATE": "cậu có hay thiền không?",
  "GAMES.PROMPTS.THEY_ARE_A_10_BUT": "họ 10 điểm nhưng...",
  "FAKE_QUESTIONS.ONE_THING_YOU_CANT_SURVIVE_WITHOUT": "một điều mà cậu không thể sống thiếu nó?",
  "FAKE_QUESTIONS.WOULD_YOU_EVER_GET_WITH_ME": "liệu c có bao giờ yêu t ko? ~ N",
  "FAKE_QUESTIONS.NETFLIX_AND_CHILL": "netflix and chill? 👀",
  "FAKE_QUESTIONS.ONE_FRIEND_UR_THANKFUL_FOR": "một người bạn c biết ơn...",
  "FAKE_QUESTIONS.HAVE_YOU_EVER_CHEATED_YOU_GOTTA_BE_HONEST_LOL": "đã cắm sừng ai bao giờ chưa, phải trả lời thật đấy lol",
  "FAKE_QUESTIONS.WHATS_UR_FAV_DRINK": "đồ uống c thích nhất là gì",
  "FAKE_QUESTIONS.HOW_OLD_DO_U_WANNA_BE_WHE_U_GET_MARRIED": "c muốn kết hôn năm bn tuổi?",
  "FAKE_QUESTIONS.FAVORITE_FOOD": "món ăn yêu thích nhất?",
  "HOME.PLAY_SCREEN.STEP_ONE.ACTION": "Đã sao chép liên kết!",
  "FAKE_QUESTIONS.DREAM_JOB": "công việc mơ ước?",
  "HOME.INBOX_SCREEN.SENTWITHLOVE": "sent with ❤️ from team NGL",
  "HOME.INBOX_SCREEN.NAME": "Tin nhắn",
  "HOME.PLAY_SCREEN.TUTORIAL.PROMPT3": "Dán liên kết của bạn!",
  "FAKE_QUESTIONS.HOW_TALL_ARE_U": "c cao bao nhiêu",
  "HOME.PLAY_SCREEN.TUTORIAL.PROMPT2": "Nhấp vào nút",
  "QUESTION.REPORT.MODAL.ACTION": "Báo cáo",
  "FAKE_QUESTIONS.YOUR_BIGGEST_INSECURITY": "cậu tự ti về điều gì nhất?",
  "HOME.PLAY_SCREEN.TUTORIAL.PROMPT4": "Đóng khung liên kết!",
  "FAKE_QUESTIONS.FAVORITE_SHOW_RN": "chương trình c đang thích nhất?",
  "HOME.PLAY_SCREEN.TUTORIAL.STEPS.THREE.TITLE": "Dán liên kết của bạn!",
  "FAKE_QUESTIONS.SINGLE": "độc thân?",
  "HOME.PLAY_SCREEN.TUTORIAL.PROMPT1": "Nhấp vào nút",
  "FAKE_QUESTIONS.OUR_BIGGEST_FEAR": "Điều mà cậu sợ nhất?",
  "FAKE_QUESTIONS.WYD": "đang làm gì đấy",
  "REENGAGEMENT.SUBTEXT.FRIDAY18": "Chia sẻ liên kết của bạn!",
  "FAKE_QUESTIONS.SPILL_SOME_TEA": "kể một bí mật đi",
  "HOME.INBOX_SCREEN.PAYWALL_BUTTON": "Ai đã gửi chúng nhỉ? 👀",
  "HOME.PLAY_SCREEN.TUTORIAL.SHARE_ON_INSTAGRAM": "Chia sẻ trên Instagram!",
  "REENGAGEMENT.SUBTEXT.SATURDAY18": "Nhấp ngay!",
  "FAKE_QUESTIONS.INTROVERT_OR_EXTROVERT": "hướng nội hay hướng ngoại?",
  "FAKE_QUESTIONS.SNAP": "snap?",
  "FAKE_QUESTIONS.SHOUT_ME_OUT": "quảng cáo tui đi",
  "HOME.PLAY_SCREEN.TUTORIAL.NEXT_STEP": "Bước tiếp theo",
  "FAKE_QUESTIONS.THE_WORST_ADVICE_YOUVE_EVER_GIVEN": "lời khuyên tệ nhất cậu từng đưa ra?",
  "FAKE_QUESTIONS.AVORITE_MOVIE_TV_SERIES_RN": "Phim/series tv cậu đang thích",
  "QUESTION.PAYWALL.RENEWAL.PRIVACY": "Riêng tư",
  "FAKE_QUESTIONS.SHOULD_I_BE_HONEST_WITH_YOU_ON_HERE": "t có nên nói thật với c ở đây không?",
  "FAKE_QUESTIONS.WHO_WAS_YOUR_CRUSH_IN_MIDDLE_SCHOOL_LMAO": "crush c hồi cấp hai lmao",
  "FAKE_QUESTIONS.DO_U_HAVE_A_DOG": "c có nuôi chó không?",
  "QUESTION.REPORT.STEP_TWO.TELL_TEAM": "Báo với Đội NGL",
  "FAKE_QUESTIONS.DO_YOU_HAVE_A_MIDDLE_NAME": "tên đệm cậu là gì?",
  "FAKE_QUESTIONS.WHATS_THE_LAST_THING_YOU_ATE": "món cậu ăn gần đây nhất là gì?",
  "SETTINGS.SHARE": "Cách chia sẻ liên kết",
  "FAKE_QUESTIONS.I_REALLY_LIKE_YOU": "mình rất thích cậu",
  "PROMPTS.ASK_ME_ANYTHING": "hỏi tôi bất kỳ điều gì một cách ẩn danh",
  "HOME.PLAY_SCREEN.TUTORIAL.SHARE_ON_TWITTER": "Chia sẻ lên Twitter!",
  "FAKE_QUESTIONS.WE_SHOULD_TALK_MORE": "mình nên nói chuyện nhiều hơn",
  "FAKE_QUESTIONS.EVER_GONE_SKINNY_DIPPING": "c đã bao giờ đi tắm tiên chưa?",
  "FAKE_QUESTIONS.NOT_GONNA_JUDGE_BUT_WHY": "t không phán xét đâu nma sao...",
  "FAKE_QUESTIONS.TELL_ME_A_FUNNY_JOKE": "kể một câu đùa đi",
  "FAKE_QUESTIONS.YOU_EVER_THINK_ABOUT_HAVING_THE_ABILITY_TO_TELEPORT": "cậu đã bao giờ nghĩ về năng lực dịch chuyển tức thời chưa?",
  "QUESTION.PAYWALL_BUTTON": "Ai đã gửi tin này",
  "REENGAGEMENT.THURSDAY18": "Tin nhắn mới 😜",
  "FAKE_QUESTIONS.YOUR_REALLY_ATTRACTIVE": "c đẹp thật đó",
  "FAKE_QUESTIONS.WHATS_YOUR_BIGGEST_INSECURITY": "cậu tự ti về điều gì nhất 🤔",
  "GENERAL.CANCEL": "Hủy",
  "HOME.PLAY_SCREEN.TUTORIAL.STEPS.ONE.TITLE.ONE": "Nhấp vào",
  "QUESTION.HINTS.TITLE": "gợi ý tin nhắn",
  "GAMES.PROMPTS.3WORDS": "nói về mình trong 3 từ, ẩn danh",
  "FAKE_QUESTIONS.DONT_LEAVE_ME_ON_OPENED": "đừng mở tin nhắn t mà không rep",
  "FAKE_QUESTIONS.WHO_YOU_TRYNA_VOTE_FOR_IN_2024": "cậu sẽ bầu cho ai trong năm 2024 👀",
  "FAKE_QUESTIONS.ARE_YOU_TALKING_TO_ANYONE": "cậu có đang nói chuyện với ai không?",
  "FAKE_QUESTIONS.HOW_OLD_ARE_YOU_AGAIN": "cậu bao nhiêu tuổi ấy nhỉ?",
  "FAKE_QUESTIONS.HOW_TALL_ARE_YOU": "cậu cao bao nhiêu??",
  "FAKE_QUESTIONS.PERSONALITY_OR_LOOKS": "tính cách hay ngoại hình?",
  "FAKE_QUESTIONS.ARE_YOU_LOOKING_TO_DATE_SOMEONE_RN": "c có đang muốn hẹn hò ai ko",
  "FAKE_QUESTIONS.WHATS_YOUR_SIGN": "cậu cung gì",
  "FAKE_QUESTIONS.WHEN_WAS_THE_LAST_TIME_YOU_WET_THE_BED": "lần cuối c tè dầm là khi nào?",
  "PROMPTS.SEND_NAME_RATE": "gửi một cái tên để mình đánh giá",
  "FAKE_QUESTIONS.DO_YOU_HAVE_ANY_PIERCINGS": "cậu có xỏ khuyên không?",
  "FAKE_QUESTIONS.WHAT_WAS_YOUR_FAVORITE_SHOW_WHEN_YOU_WERE_A_KID": "chương trình cậu thích nhất hồi bé?",
  "FAKE_QUESTIONS.YO_STOP_LEAVING_ME_ON_READ": "yo đừng bơ tin nhắn t nữa",
  "FAKE_QUESTIONS.YOURE_CUTE": "c cute đó",
  "SETTINGS.WHO_IT_WORKS.DESCRIPTION.TWO": "Bạn có thể chia sẻ nó ở bất cứ đâu trên internet!",
  "FAKE_QUESTIONS.DO_YOU_WANT_KIDS_EVENUTALLY": "sau này cậu muốn có con không?",
  "FAKE_QUESTIONS.WHATS_YOUR_FAV_SPORT": "môn thể thao c thích nhất?",
  "FAKE_QUESTIONS.HAVE_COVID_ANY_SHOW_RECOMENDATIONS": "Mình bị covid, cậu đề xuất show gì không?",
  "FAKE_QUESTIONS.THE_WEIRDEST_PLACE_YOUVE_EVER_GONE_TO_THE_BATHROOM": "nơi dị nhất mà cậu từng đi vệ sinh?",
  "FAKE_QUESTIONS.KNOW_WHAT_YOU_DID": "T biết cậu đã làm gì",
  "FAKE_QUESTIONS.HAVE_YOU_EVER_GOTTEN_IN_A_FIST_FIGHT": "c đã đánh nhau bao giờ chưa?",
  "FAKE_QUESTIONS.WHEN_WAS_THE_LAST_TIME_YOU_CRIED": "lần cuối c khóc là khi nào?",
  "FAKE_QUESTIONS.WHAT_COLOR_IS_YOUR_ROOM": "phòng cậu màu gì?",
  "FAKE_QUESTIONS.YOUR_CELEB_CRUSH": "người nổi tiếng mà c crush?",
  "QUESTION.REPORT.STEP_ONE.BULLYING": "Bắt nạt hay quấy rối",
  "HOME.PLAY_SCREEN.STEP_TWO.BUTTON": "Chia sẻ!",
  "FAKE_QUESTIONS.HOW_MANY_STUFFED_ANIMALS_YOU_OWN": "cậu có bao nhiêu thú bông?",
  "FAKE_QUESTIONS.WHATS_IN_UR_SPOTIFY_TOP_SONGS": "các bài top trên spotify của c là gì",
  "FAKE_QUESTIONS.YOUR_LAST_SONG_ON_YOUR_SPOTIFY": "bài hát c nghe gần đây nhất trên spotify?",
  "FAKE_QUESTIONS.HAT_IS_YOUR_SHOE_SIZE": "Cậu đi giày cỡ bao nhiêu?",
  "FAKE_QUESTIONS.WHAT_ARE_YOU_WEARING": "cậu đang mặc đồ gì?",
  "FAKE_QUESTIONS.ARE_YOU_STRAIGHT": "cậu có thẳng không?",
  "REENGAGEMENT.WEDNESDAY18": "Chia sẻ liên kết của bạn 😛",
  "FAKE_QUESTIONS.YOURE_BEST_FRIEND": "cậu là bạn thân nhất của tớ",
  "FAKE_QUESTIONS.WHAT_HAVE_YOU_GOTTEN_DETENTION_FOR": "cậu từng bị phạt vì gì?",
  "QUESTION.REPORT.STEP_TWO.DELETE_MESSAGE": "Xóa tin nhắn",
  "HOME.PLAY_SCREEN.TITLE": "Nhận tin nhắn ẩn danh!",
  "SETTINGS.HELP": "Tôi cần trợ giúp",
  "FAKE_QUESTIONS.HAVE_U_SEEN_BREAKING_BAD": "c xem breaking bad chưa",
  "FAKE_QUESTIONS.YOU_SHOULD_POST_MORE_SELFIES": "c nên đăng ảnh tự sướng nhiều hơn 💕",
  "FAKE_QUESTIONS.DID_YOU_WATCH_GAME_OF_THRONES": "cậu xem game of thrones chưa?",
  "FAKE_QUESTIONS.THE_LONGEST_TIME_YOUVE_EVER_GONE_WITHOUT_SHOWERING": "lần lâu nhất cậu không tắm là mấy ngày?",
  "QUESTION.REPORT.STEP_TWO.BLOCK_USER": "Chặn người dùng",
  "QUESTION.REPORT.STEP_ONE.DONT_LIKE_IT": "Tôi không thích nó",
  "FAKE_QUESTIONS.HOW_MANY_SELFIES_DO_YOU_TAKE_A_DAY": "mỗi ngày cậu chụp bn ảnh tự sướng?",
  "FAKE_QUESTIONS.WHATS_UR_FAV_SONG": "c thích bài hát nào nhất",
  "FAKE_QUESTIONS.THE_WORST_DATE_YOUVE_EVER_BEEN_ON": "buổi hẹn tệ nhất của cậu?",
  "FAKE_QUESTIONS.WHOS_UR_CRUSH": "crush c là ai",
  "FAKE_QUESTIONS.YOU_A_HOMIE": "c là bạn yêu",
  "FAKE_QUESTIONS.THE_MOST_EMBARRASSING_THING_YOUVE_EVER_DONE": "điều xấu hổ nhất cậu từng làm?",
  "FAKE_QUESTIONS.YOU_LIT": "c thật ngầu",
  "FAKE_QUESTIONS.WHO_DO_YOU_MISS_THE_MOST": "cậu nhớ ai nhất",
  "FAKE_QUESTIONS.WOULD_YOU_EVER_BE_FWB": "c có bao giờ làm fwb ko",
  "QUESTION.REPORT.TITLE": "Vì sao bạn muốn báo cáo câu hỏi này?",
  "ONBOARDING.FIRST_STEP.BUTTON": "Bắt đầu nào!",
  "FAKE_QUESTIONS.DO_YOU_HAVE_ANY_CUTE_FRIENDS_FOR_ME_LMAO": "cậu quen ai dễ thương cho mình k lmao",
  "QUESTION.HINTS.TIME.DESCRIPTION": "đã gửi vào",
  "FAKE_QUESTIONS.UH_WHAT_DID_YOU_EAT_FOR_BREAKFAST": "uh sáng nay c ăn gì?",
  "REENGAGEMENT.MONDAY17": "Nhận tin nhắn ẩn danh 🤫",
  "FAKE_QUESTIONS.ANY_PETS": "cậu có nuôi con gì không?",
  "REENGAGEMENT.MONDAY18": "Tin nhắn mới 🧡",
  "QUESTION.HINTS.PHONE": "điện thoại",
  "FAKE_QUESTIONS.YOU_GOT_A_SNEAKY_LINK": "có sneaky link không?",
  "FAKE_QUESTIONS.WHATS_UR_ORITENATION": "xu hướng tính dục của c là gì",
  "FAKE_QUESTIONS.WHATS_THE_STUPIDEST_THING_YOU_THOUGHT_AS_A_KID": "thứ ngớ ngẩn nhất cậu từng ăn hồi bé?",
  "FAKE_QUESTIONS.WHAT_MUSIC_DO_YOU_LISTEN_TO": "cậu hay nghe nhạc gì",
  "FAKE_QUESTIONS.YOU_WILD_FOR_WHAT_YOU_DID": "c làm vậy đỉnh quá luôn",
  "PROMPTS.SEND_ME_ANONYMOUS_MESSAGES": "gửi cho mình tin nhắn ẩn danh nha!",
  "FAKE_QUESTIONS.IS_NGL_THE_BEST_APP_THO": "ngl có phải app hay nhất ko :)",
  "GENERAL.AND": "và",
  "QUESTION.PAYWALL.RESTORE": "khôi phục",
  "PROMPTS.SEND_ME_ANONYMOUS_COMPLIMENTS": "gửi cho mình lời khen ẩn danh nha!",
  "SETTINGS.WHO_IT_WORKS.DESCRIPTION.ONE": "Bạn có thể nhận tin nhắn bằng cách chia sẻ liên kết NGL trên story hoặc thêm nó vào tiểu sử của bạn",
  "QUESTION.PAYWALL.UNLOCK": "Mở khóa",
  "FAKE_QUESTIONS.YOUR_FAVORITE_PART_OF_YOUR_BODY": "c thích phần nào nhất trên cơ thể mình?",
  "FAKE_QUESTIONS.ARE_YOU_A_BACK_SEAT_DRIVER": "khi ngồi sau xe cậu có hay chỉ bảo người lái không?",
  "FAKE_QUESTIONS.HAVE_YOU_EVER_WATCHED_HARRY_POTTER": "c xem harry potter bao giờ chưa?",
  "FAKE_QUESTIONS.YOU_HAVE_GOOD_STYLE": "phong cách c đẹp đó",
  "QUESTION.REPORT.STEP_ONE.SPAM": "Tin rác",
  "FAKE_QUESTIONS.PLEASE_GIVE_ME_PICKUP_LINES_THAT_ALWAYS_WORK": "xin cho t các câu tán luôn đổ",
  "FAKE_QUESTIONS.ARE_YOU_JUDGEMENTAL": "cậu có hay phán xét không",
  "FAKE_QUESTIONS.HOW_BIG_OF_NERD_ARE_YOU_1_TO_10": "trên thang từ 1 đến 10, cậu mọt sách độ mấy",
  "REENGAGEMENT.SUNDAY17": "Nhận tin nhắn ẩn danh 💌",
  "REENGAGEMENT.SUNDAY18": "Tin nhắn mới ✌️",
  "FAKE_QUESTIONS.EVERYTHING_OK": "mọi thứ ổn ko?",
  "FAKE_QUESTIONS.DO_YOU_SPEAK_ANOTHER_LANGUAGE": "cậu có nói được ngoại ngữ nào không?",
  "FAKE_QUESTIONS.WHATS_UR_FAVORITE_FOOD": "c thích nhất món gì?",
  "FAKE_QUESTIONS.WHATS_YOUR_DREAM_HOUSE": "ngôi nhà mơ ước của cậu ntn",
  "FAKE_QUESTIONS.DO_YOU_HAVE_TRUST_ISSUES": "cậu có vấn đề về lòng tin không?",
  "FAKE_QUESTIONS.WHAT_TIME_DID_YOU_FALL_ASLEEP_LAST_NIGHT": "đêm qua mấy giờ c ngủ?",
  "PROMPTS.FLOOD_MY_INBOX": "có giỏi thì nhắn đầy hòm thư của mình",
  "FAKE_QUESTIONS.HOW_ARE_YOU_TODAY": "Hôm nay cậu thế nào ❤️",
  "HOME.PLAY_SCREEN.UPLOAD_PICTURE": "Tải ảnh lên",
  "FAKE_QUESTIONS.CRAZIEST_PICKUP_LINE_THAT_WORKED": "câu tán điên rồ nhất mà cưa đổ thật?",
  "QUESTION.HINTS.DESCRIPTION": "gợi ý về người gửi tin nhắn này",
  "REENGAGEMENT.FRIDAY18": "Nhận thêm tin nhắn 🥰",
  "QUESTION.HINTS.LOCATION.TITLE": "vị trí",
  "HOME.INBOX_SCREEN.EMPTY.TITLE": "Hòm thư của bạn còn trống",
  "FAKE_QUESTIONS.U_BUSY_THIS_WEEKEND": "cuối tuần này bận ko?",
  "FAKE_QUESTIONS.I_LOVE_UUUUUU": "iu cậuuuuuu!!",
  "FAKE_QUESTIONS.OPINION_ON_BIRDS": "ý kiến về loài chim?",
  "FAKE_QUESTIONS.BODY_COUNT": "yêu mấy người rồi 😳?",
  "FAKE_QUESTIONS.HAVE_A_CRUSH_ON_YOU": "Tớ crush cậu",
  "FAKE_QUESTIONS.WHOS_UR_BEST_FRIEND": "bạn thân của c là ai",
  "SETTINGS.WHAT_IS_NGL.DESCRIPTION": "NGL là một cách thú vị để nhận tin nhắn ẩn danh từ bạn bè của mình",
  "FAKE_QUESTIONS.DO_YOU_LOVE_UR_LIFE_X": "cậu có yêu cuộc sống của mình ko? x",
  "FAKE_QUESTIONS.IGGEST_RED_FLAGS_FOR_A_GIRL": "Các red flag lớn nhất ở con gái?",
  "FAKE_QUESTIONS.DID_YOU_HAVE_AN_IMAGINARY_FRIEND": "cậu có một người bạn tưởng tượng không?",
  "HOME.PLAY_SCREEN.STEP_ONE.TITLE": "Bước 1: Sao chép liên kết của bạn",
  "ONBOARDING.FIRST_STEP.TERMS_PRIVACY.FOUR": "Chính sách quyền riêng tư",
  "HOME.INBOX_SCREEN.EMPTY.GET_MESSAGES": "Nhận tin nhắn!",
  "FAKE_QUESTIONS.WHAT_PHONE_DO_YOU_HAVE": "cậu dùng điện thoại gì?",
  "GENERAL.SOMETHING_WENT_WRONG": "Đã xảy ra lỗi!",
  "HOME.PLAY_SCREEN.TUTORIAL.STEPS.FOUR.TITLE": "Đóng khung liên kết",
  "ONBOARDING.FIRST_STEP.TERMS_PRIVACY.TWO": "Điều khoản sử dụng",
  "QUESTION.HINTS.TIME.TITLE": "thời gian gửi",
  "REENGAGEMENT.SUBTEXT.THURSDAY18": "Nhấp vào đây!",
  "FAKE_QUESTIONS.AVE_YOU_EVER_BEEN_FIRED_FROM_A_JOB": "Cậu đã bao giờ bị đuổi việc chưa?",
  "FAKE_QUESTIONS.HAVE_YOU_EVER_GIVEN_A_HICKEY": "c đã bao giờ để lại dấu hôn chưa?",
  "QUESTION.PAYWALL.DESCRIPTION": "thành viên pro có thể xem gợi ý độc quyền cho từng tin nhắn",
  "FAKE_QUESTIONS.WHO_DO_YOU_HAVE_PINNED_ON_IMESSAGE": "cậu đã ghim ai trên imessage",
  "ONBOARDING.SECOND_STEP.TITLE": "Tên tài khoản Instagram của bạn là gì?",
  "ONBOARDING.FIRST_STEP.TITLE": "Nhận tin nhắn ẩn danh trên Instagram!",
  "FAKE_QUESTIONS.WHATS_YOUR_NUMBER_ONE_SONG_ON_SPOTIFY": "bài hát số một của c trên spotify",
  "FAKE_QUESTIONS.ARE_YOU_CLOSE_WITH_YOUR_PARENTS": "cậu có thân với bố mẹ không?",
  "FAKE_QUESTIONS.HOW_TALL_R_U": "c cao bn",
  "FAKE_QUESTIONS.BIGGEST_RED_FLAGS_IN_A_GUY": "các red flag lớn nhất ở con trai?",
  "FAKE_QUESTIONS.HOTTEST_SPORT": "môn thể thao hot nhất? 🥵",
  "FAKE_QUESTIONS.WHO_DO_YOU_TEXT_THE_MOST": "cậu hay nhắn tin với ai nhất?",
  "HOME.PLAY_SCREEN.TUTORIAL.TITLE": "Hướng dẫn thêm Liên kết vào tin đăng",
  "FAKE_QUESTIONS.DO_YOU_SNORE": "cậu có hay ngáy không?",
  "HOME.INBOX_SCREEN.EMPTY.DESCRIPTION": "Chia sẻ liên kết của bạn để nhận các câu hỏi vào hòm thư!",
  "FAKE_QUESTIONS.YOUR_FAVORITE_HOBBY": "sở thích lớn nhất của c?",
  "FAKE_QUESTIONS.WHO_ARE_YOUR_BEST_GIRL_FRIENDS": "các bạn nữ c thân nhất là ai",
  "FAKE_QUESTIONS.FAVORITE_MOVIE": "bộ phim yêu thích nhất?",
  "FAKE_QUESTIONS.WHOS_UR_WORST_ENEMY": "kẻ thù lớn nhất của c là ai 😈",
  "ONBOARDING.FIRST_STEP.TERMS_PRIVACY.THREE": "và đã đọc và đồng ý với",
  "FAKE_QUESTIONS.IS_IT_TRUE": "thật ko???",
  "FAKE_QUESTIONS.HOW_ARE_YOU_FEELING_TODAY": "hôm nay cậu thế nào :)",
  "FAKE_QUESTIONS.HOW_MANY_EXES_DO_YOU_HAVE": "cậu có mấy ny cũ rồi?",
  "FAKE_QUESTIONS.WHO_WAS_YOUR_FIRST_KISS": "lần đầu tiên là hôn ai?",
  "GENERAL.NO": "Không",
  "SETTINGS.WHO_IT_WORKS.TITLE": "Nó hoạt động như thế nào?",
  "FAKE_QUESTIONS.WHATS_UR_FAV_TV_SHOW": "c thích chương trình tv nào nhất",
  "GAMES.PROMPTS.CRUSH": "kể về crush một cách ẩn danh",
  "QUESTION.HINTS.NGL_ID": "id ngl",
  "FAKE_QUESTIONS.WHATS_UR_FAV_FOOD": "c thích nhất món gì",
  "FAKE_QUESTIONS.YOU_SHOULD_GET_A_TATTOO": "c nên đi xăm",
  "QUESTION.PAYWALL.TITLE": "Ai đã gửi tin này?",
  "FAKE_QUESTIONS.WHO_YOU_TRYNA_GET_WITH": "đang cố cưa ai đấy 👀",
  "REENGAGEMENT.SUBTEXT.WEDNESDAY18": "Nhấp vào đây!",
  "FAKE_QUESTIONS.YOUR_WORST_PERSONALITY_CHARACTERISTIC": "tính xấu nhất của cậu?",
  "QUESTION.PAYWALL.RENEWAL.TWO": "mỗi tuần.",
  "FAKE_QUESTIONS.WHAT_ARE_UR_PLANS_THIS_WEEKEND": "cuối tuần này c định làm gì?",
  "FAKE_QUESTIONS.WYD_TOMORROW": "mai c làm gì",
  "REENGAGEMENT.SATURDAY18": "Chia sẻ liên kết của bạn 😇",
  "FAKE_QUESTIONS.HATS_UR_FAV_BRAND_<3": "c thích hãng nào nhất?? <3",
  "SETTINGS.DELETE": "Xóa tài khoản",
  "SETTINGS.FOLLOW": "Theo dõi chúng tôi trên IG️",
  "FAKE_QUESTIONS.CAN_WE_BE_BESTIES": "mình làm bạn thân được ko",
  "FAKE_QUESTIONS.I_MISS_YOU": "mình nhớ cậu",
  "FAKE_QUESTIONS.HAVE_YOU_EVER_CRIED_DURING_A_MOVIE": "cậu đã bao giờ khóc khi xem phim chưa 🤷",
  "FAKE_QUESTIONS.NAME_ALL_YOUR_EXES": "kể tên hết các nyc đi",
  "SETTINGS.DELETE_MODAL.DESCRIPTION": "Nếu bạn xóa tài khoản, bạn sẽ mất quyền truy cập vào tên người dùng và mọi câu hỏi của mình",
  "FAKE_QUESTIONS.THE_WORST_FOOD_YOU_EVER_EATEN": "món tệ nhất cậu từng ăn?",
  "FAKE_QUESTIONS.WHEN_WAS_YOUR_FIRST_KISS": "lần đầu cậu hôn là khi nào?",
  "FAKE_QUESTIONS.HE_WEIRDEST_TREND_YOUVE_DONE": "Trend dị nhất c từng đu",
  "SETTINGS.WHAT_IS_NGL.TITLE": "NGL là gì?",
  "SETTINGS.TUTORIAL.MODAL.GOT.IT": "Hiểu rồi!",
  "HOME.PLAY_SCREEN.STEP_TWO.TITLE": "Bước 2: Chia sẻ liên kết trên Story Instagram của mình",
  "QUESTION.REPLY": "trả lời",
  "FAKE_QUESTIONS.A_SECRET_YOU_KEPT_FROM_YOUR_PARENTS_2": "một điều cậu giấu bố mẹ 👀",
  "PROMPTS.DROP_NAME_TBH": "thả một tên để mình nêu ý kiến",
  "FAKE_QUESTIONS.BIGGEST_REGRET": "điều hối hận lớn nhất?",
  "FAKE_QUESTIONS.DOGS_OR_CATS": "chó hay mèo?",
  "FAKE_QUESTIONS.WOULD_YOU_SAY_YES_IF_I_ASKED_YOU_OUT": "nếu t muốn date c thì c có đồng ý không - A",
  "GAMES.PROMPTS.NEVER_HAVE_I_EVER": "gửi mình một 'mình chưa bao giờ' ẩn danh",
  "FAKE_QUESTIONS.HAVE_YOU_DONE_DRUGS": "chơi đồ bao giờ chưa 🍃",
  "FAKE_QUESTIONS.YOUR_WORST_HABIT": "thói quen xấu nhất của cậu?",
  "QUESTION.HINTS.COUNTRY": "quốc gia",
  "FAKE_QUESTIONS.HAVE_ANY_NETFLIX_RECOMENDATIONS": "c có đề xuất xem gì trên netflix ko??",
  "FAKE_QUESTIONS.OWS_YOU_DAY_GOING": "Hôm nay cậu thế nào ??!",
  "FAKE_QUESTIONS.WORST_MOVIE_YOUVE_EVER_WATCHED": "bộ phim dở nhất c từng xem?",
  "FAKE_QUESTIONS.WHAT_DID_YOU_DREAM_ABOUT_LAST_NIGHT": "cậu mơ thấy gì đêm qua?",
  "FAKE_QUESTIONS.WHY_DOESNT_MY_CRUSH_LIKE_ME_BACK": "sao crush không thích t 😭",
  "ONBOARDING.FIRST_STEP.TERMS_PRIVACY.ONE": "Bằng cách tiếp tục, bạn đồng ý với",
  "FAKE_QUESTIONS.WHAT_WAS_THE_BEST_DAY_SO_FAR_THIS_YEAR": "năm nay có ngày nào là tuyệt nhất?",
  "FAKE_QUESTIONS.WHOS_YOUR_LAST_IG_SEARCH": "c tìm kiếm ai trên ig gần đây nhất?",
  "PROMPTS.TELL_ME_WHAT_YOU_THINK_ABOUT_ME": "nói cho mình cậu THỰC SỰ nghĩ gì về mình!"
}